server:
  port: 9090
  
spring:
  application:
    name: ADDRESS-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: micro
    url: jdbc:mysql://localhost:3306/micro_db
    username: micro
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
